# Generated by Django 4.1.7 on 2023-03-03 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.Gallery.get_file_mame)),
                ('desc', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReservationFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$')])),
                ('persons', models.SmallIntegerField()),
                ('message', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_processed_date', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.SmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=False)),
                ('desc', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ingridients', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=main_page.models.Dish.get_file_mame)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.dishcategory')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
