# Generated by Django 4.1.7 on 2023-03-01 09:46

from django.db import migrations, models
import django.utils.timezone
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=main_page.models.Dish.get_file_mame),
            preserve_default=False,
        ),
    ]
